### ISSUE TITLE
"Device not found"

### ISSUE THREAD

**Issue by Pesoen** [mx0c/Corsair-Void-Pro-Battery-Overlay#2]
i have a void pro wireless, and it keeps saying device not found.. tried turning my headset on and off, and connected using usb and without it. clicking the "Manually Select Device" button does nothing.

is there something specific i need to do or install? i have iCUE installed and it can see the battery percentage just fine.

**Comment by mx0c** [comment]
hmm weird... Could you provide a screenshot of the found devices under the manually select device tab ? Also you might need to wait a little between the manually selection of the device.

**Comment by Pesoen** [comment]
nothing comes up when clicking the manually select device button(it appears as a button) have now had it running for an hour or so, still just red text saying device not found.

i ran the program as an admin, since it failed at first..

does the headset need to be updated to the latest firmware? currently running an older 0.15 version, because the newer updates disable a feature i use frequently(it did on my regular Void wireless, not the pro version, so i assume it's the firmware that was the cause)

**Comment by Pesoen** [comment]
connected my regular Void wireless still nothing happening when i click the manually selected device button(still a button) and still just red text saying device not found..

**Comment by mx0c** [comment]
Interesting, then probably the product id is wrong configured in the application. I didn't know that it could vary across devices. Could you provide me the Product ID (PID) of your Headset? You can find it under Control Panel ->Device Manager then on the tab Audio, Video and Gamecontroller -> Corsaird Void Pro -> Right click -> properties -> details tab -> Hardware-Id's. Then you should see a string that looks like something like this: `USB\VID_1B1C&PID_0A14&MI_00`.

**Comment by Pesoen** [comment]
i got two of them.
top one is this "USB\VID_1B1C&PID_0A16&REV_0000&MI_00"
bottom one is this "USB\VID_1B1C&PID_0A16&MI_00"

maybe my headsets a newer revision? considering i can see yours says 14, while mine is 16..

**Comment by mx0c** [comment]
Yes, you have probably a newer version. I just added the ability to change the PID in the TrayIcon ContextMenu. Let me know if it works.

**Comment by Pesoen** [comment]
that worked, now the "manually select device" thingy also works, its now a list that folds out with ID's :) thanks for the help, and keep up the good work :D
