### ISSUE TITLE
Awesome Discovery.

### ISSUE THREAD

**Issue by Pesoen** [mx0c/Corsair-Void-Pro-Battery-Overlay#3]
I have a Corsair Void RGB wireless, and since you added the option to change the PID, i decided to try if it would work.. Turns out it does work. It shows the battery % or the battery image properly and everything.

PID: 1B27

Keep up the awesome work 👍

**Comment by Pesoen** [comment]
i have a suspicion it will work with any Corsair Void version that is wireless, but i can't know for sure..

**Comment by mx0c** [comment]
Great to hear gonna add this in a supported devices section of the readme when i have time :) Thanks for your feedback.

**Comment by Pesoen** [comment]
you are very welcome :) happy to help when you helped me :D
